# yamllint disable rule:line-length
# yamllint disable rule:braces
name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  tests:
    name: Testing with PHP ${{ matrix.php-version }} ${{ matrix.description }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
        coverage: ['none']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: ${{ matrix.coverage }}
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      - name: Parallel PHP Lint
        run: |
          vendor/bin/parallel-lint --exclude vendor .
          
      - name: PHP Unit tests
        run: |
          vendor/bin/phpunit --no-coverage
